name: Run Trading Result

on:
  workflow_dispatch:

jobs:
  run-result:
    runs-on: ubuntu-latest

    steps:
      - name: Call Result API
        run: curl -A "Mozilla/5.0" https://bet999.gamer.gd/result.php
